### ISSUE TITLE
Bowtie Indices relative paths not supported

### ISSUE THREAD

**Issue by rcao5** [nellore/rail#68] opened 2017-08-28 21:37 UTC
While trying to run the [Drosophila example](http://docs.rail.bio/tutorial/#local-and-parallel-modes-drosophila-examples) from the Tutorial, I've noticed that providing the relative paths to the bowtie indices throws a runtime error. I'm calling the following command from an empty directory `railtests`, and the `Drosophila_melanogaster` directory containing the bowtie indices is one level above `railtests`:

`[root@ip-10-5-163-113 railtests]# rail-rna go local -x ../Drosophila_melanogaster/UCSC/dm3/Sequence/BowtieIndex/genome ../Drosophila_melanogaster/UCSC/dm3/Sequence/Bowtie2Index/genome -m https://raw.githubusercontent.com/nellore/rail/master/ex/dm3_example.manifest`

The runtime error which can be found in `/rail-rna_logs/precoverage/dp.reduce.log/0.0.log`:

```
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/home/ec2-user/raildotbio/rail-rna/rna/steps/coverage_pre.py", line 130, in <module>
    os.path.expandvars(args.bowtie_idx)
  File "/home/ec2-user/raildotbio/rail-rna/rna/utils/bowtie_index.py", line 27, in __init__
    raise RuntimeError('No Bowtie index files with prefix "%s"' % idx_prefix)
RuntimeError: No Bowtie index files with prefix "../Drosophila_melanogaster/UCSC/dm3/Sequence/BowtieIndex/genome"
```

While the issue can be fixed simply by providing the full paths to the bowtie indices, I feel it would be best to support relative paths in the future, or to note this requirement in the documentation for now.

**Comment by nellore** [comment] 2017-08-29 02:00
You're right! Support for relative paths was intended, but apparently coverage_pre couldn't accommodate a relative path. Fixed in  ff58d2198e1a8f213fce04bd96d9fb65b01a3c58.

**Closed by nellore** 2017-08-29 02:00 UTC
